extends:
- "./node_modules/prettier-stylelint/config.js"
- stylelint-config-standard
- stylelint-config-recommended
plugins:
- stylelint-order
- stylelint-scss
ignoreFiles:
- "**/node_modules/**"
rules:
  at-rule-no-unknown:
  scss/at-rule-no-unknown: true
  order/properties-alphabetical-order: true
